---
- hosts: localhost
  connection: local
  become: true

  tasks:
    - name: distribution | debug
      tags: always
      debug: msg="{{ ansible_distribution }} {{ ansible_distribution_release }}"

    - include: roles/base/tasks/main.yml
    - include: roles/desktop/tasks/main.yml
