- block:

  # Make sure users exist on the system
  - import_tasks: users/thom.yml
  - import_tasks: users/root.yml

  # Install basic system utilities
  - import_tasks: system/default.yml
  - import_tasks: system/autofs.yml
  - import_tasks: system/flatpak.yml

  ## install software
  - import_tasks: software/nextcloud.yml
  - import_tasks: software/vscode.yml

  rescue:
    - set_fact: task_failed=true
