- name: "Load aliases in .bashrc file"
  blockinfile:
    path: "/home/thom/.bashrc"
    block: |
      if [ -f ~/.aliases ]; then
        source ~/.aliases
      fi

- name: users | thom | copy dotfiles
  tags: dotfiles,users,thom,users,vim,zsh
  copy:
    src: users/thom/{{ item.src }}
    dest: /home/thom/{{ item.dest }}
    owner: thom
    group: thom
    mode: 0600
  with_items:
    - { src: 'aliases', dest: '.aliases' }
    - { src: 'vimrc', dest: '.vimrc' }
