- name: system | desktop environment | install kde plasma
  tags: desktop,laptop,kde-plasma
  package:
    name:
      - kde-plasma-desktop
      - pkexec
    state: latest

# - name: system | network | fix network manager
#   tags: laptop,wifi-fix
#   community.general.kdeconfig:
#     path: /etc/NetworkManager/NetworkManager.conf
#     values:
#       - group: ifupdown
#         key: Managed
#         value: true
        