- name: system | flatpak | install packages
  tags: desktop,laptop,flatpak
  apt:
    pkg: 
      - flatpak
      - plasma-discover-backend-flatpak
    state: latest
    update_cache: true

- name: system | flatpak | add flatpak repository
  tags: desktop,laptop,flatpak
  become: yes
  flatpak_remote:
    name: flathub
    flatpakrepo_url: https://flathub.org/repo/flathub.flatpakrepo
    method: system
    state: present