- name: Add backports
  tags: desktop,laptop,flatpak
  apt_repository:
    repo: deb http://deb.debian.org/debian {{ ansible_distribution_release }}-backports main
    state: present
    filename: backports
    update_cache: yes
  when: (ansible_distribution == 'Debian')

- name: Install Flatpak
  tags: desktop,laptop,flatpak
  apt:
    pkg: 
      - flatpak
      - plasma-discover-backend-flatpak
    state: latest
    default_release: "{{ ansible_distribution_release}}-backports"
    update_cache: true