# - name: software | network | verify tailscale is installed
#   tags: desktop,laptop,server,tailscale
#   package:
#     name: tailscale
#     state: present
#   check_mode: true
#   ignore_errors: yes
#   register: tailscale_check

# - name: software | network | check tailscale register
#   tags: tailscale
#   debug:
#     msg: "{{ tailscale_check }}"

- name: software | network | download tailscale install script
  tags: desktop,laptop,server,tailscale
  get_url:
    url: https://tailscale.com/install.sh
    dest: /tmp/_ansible/install_tailscale.sh
    mode: 0755
  when: not "'tailscale' in ansible_facts.packages"

- name: software | network | verify tailscale is
  tags: desktop,laptop,server,tailscale
  shell: /tmp/_ansible/install_tailscale.sh
  when: not "'tailscale' in ansible_facts.packages"
