---
- hosts: localhost
  become: true
  gather_facts: yes

  tasks:
    - name: Distribution
      debug: msg="{{ ansible_distribution }} {{ ansible_distribution_release }}"


    - name: Add backports
      apt_repository:
        repo: deb http://deb.debian.org/debian {{ ansible_distribution_release }}-backports main
        state: present
        filename: backports
        update_cache: yes
      when: (ansible_distribution_release == 'bullseye') or
        (ansible_distribution_release == 'bookworm')

    - name: Install Flatpak
      apt:
        pkg: 
          - flatpak
          - plasma-discover-backend-flatpak
        state: latest
        default_release: "{{ ansible_distribution_release}}-backports"
        update_cache: true