- name: software | graphics | get darktable signing key
  tags: desktop,darktable
  ansible.builtin.get_url:
    url:  https://download.opensuse.org/repositories/graphics:darktable/Debian_12/Release.key
    dest: /etc/apt/keyrings/packages.darktable.org.asc

- name: software | graphics | add darktable repository
  tags: desktop,darktable
  apt_repository:
    repo: "deb [signed-by=/etc/apt/keyrings/packages.darktable.org.asc] http://download.opensuse.org/repositories/graphics:/darktable/Debian_12/ /"
    filename: obs_darktable
    state: present
    update_cache: yes

- name: software | browser | install darktable
  tags: desktop,darktable
  apt:
    name: darktable
    state: present
