- name: Install required system packages
  tags: desktop,laptop,vscode
  apt:
    pkg:
      - gnupg2
      - software-properties-common
      - apt-transport-https
      - curl
    state: latest
    update_cache: true

- name: Add Microsoft GPG key
  tags: desktop,laptop,vscode
  apt_key:
    url: https://packages.microsoft.com/keys/microsoft.asc
    state: present

- name: Add VS Code repository
  tags: desktop,laptop,vscode
  apt_repository:
    repo: deb [arch=amd64] https://packages.microsoft.com/repos/vscode stable main
    state: present

- name: Update apt and install VS Code
  tags: desktop,laptop,vscode
  apt:
    name: code
    state: latest
    update_cache: true

