- name: system | utilities | install utility packages
  tags: base,desktop,laptop,server
  package:
    name:
      - bat
      - exa
      - htop
      - nmap
      - traceroute
      - vim-nox
      - wget
      - zsh
    state: latest