- name: "Load aliases in .bashrc file"
  blockinfile:
    path: "/home/thom/.bashrc"
    block: |
      if [ -f ~/.aliases ]; then
        source ~/.aliases
      fi

- name: users | thom | copy dotfiles
  #tags: dotfiles,users,thom,users,vim,zsh
  copy:
    src: users/thom/{{ item.src }}
    dest: /home/thom/{{ item.dest }}
    owner: thom
    group: thom
    mode: 0600
  with_items:
    - { src: 'aliases', dest: '.aliases' }
    - { src: 'vimrc', dest: '.vimrc' }

- name: users | thom | single click selects
  tags: users,thom
  community.general.kdeconfig:
    path: /home/thom/.config/kdeglobals
    values:
      - group: KDE
        key: SingleClick
        value: false
    owner: thom
    group: thom
    mode: 0400

- name: users | thom | caps lock as compose
  tags: users,thom
  community.general.kdeconfig:
    path: /home/thom/.config/kxkbrc
    values:
      - group: Layout
        key: Options
        value: 'compose:caps'
      - group: Layout
        key: ResetOldOptions
        value: true
    owner: thom
    group: thom
    mode: 0400

- name: user | thom | power notifications
  tags: users,thom
  community.general.kdeconfig:
    path: /home/thom/.config/devicenotifications.notifyrc
    values:
      - group: Event/safelyRemovable
        key: Action
        value: Popup
      - group: Event/safelyRemovable
        key: Execute
        value: ''
      - group: Event/safelyRemovable
        key: Logfile
        value: ''
      - group: Event/safelyRemovable
        key: TTS
        value: ''
        
- name: user | thom | previous session
  tags: users,thom
  community.general.kdeconfig:
    path: /home/thom/.config/ksmserverrc
    values:
      - group: General
        key: loginMode
        value: emptySession
      - group: 'LegacySession: saved at previous logout'
        key: count
        value: 0
      - group: 'Session: saved at previous logout'
        key: count
        value: 0

# - name: software | transmission | create directories
#   tags: users,thom
#   file:
#     path: /home/thom/{{ item }}
#     state: directory
#     owner: thom
#     group: thom
#     mode: 0750
#   with_items:
#     - .config/transmission-remote-gtk

# - name: software | transmission | copy user config file
#   tags: users,thom
#   copy:
#     src: transmission-remote-gtk/config.json
#     dest: /home/thom/.config/transmission-remote-gtk/config.json
#     owner: thom
#     group: thom
#     mode: 0640